apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-frontend.fullname" . }}-config
  labels:
    {{- include "todo-frontend.labels" . | nindent 4 }}
data:
  BACKEND_API_URL: {{ .Values.config.backendApiUrl | quote }}
  APP_NAME: {{ .Values.config.appName | quote }}
